name: Test Student Scripts

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run student script
        run: |
          chmod +x student_script.sh
          ./student_script.sh > output.txt

      - name: Compare output
        run: |
          if ! diff output.txt expected_output.txt; then
            echo "Output does not match expected result:"
            diff output.txt expected_output.txt || true
            exit 1
          fi
